# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-13 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=30, null=True, unique=True, verbose_name='User name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Site access')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Admin access')),
                ('is_email_confirmed', models.BooleanField(default=False, verbose_name='Email confirmed')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Accounts',
                'verbose_name': 'Account',
            },
        ),
    ]
